# Configuration parameters used by ./scripts/update_entity_relations.py
- title: Global Overview
  description: An overview of the entire submission schema.
  model: submission_centric_schema.yaml
  tree_root: true
  include_attributes: false
- title: Sample, Biospecimen, & Individual
  description: Focusses on the relation between Sample, Biospecimen, and Individual.
  model: submission_centric_schema.yaml
  classes: ["sample", "biospecimen", "individual"]
  tree_root: false
  include_attributes: false
- title: Experiment, Sample, & File
  description: Focusses on the relation between Experiment, Sample, and File.
  model: submission_centric_schema.yaml
  classes: ["experiment", "sample", "file"]
  tree_root: false
  include_attributes: false
