# Configuration parameters used by ./scripts/update_entity_relations.py
- title: Global Overview
  description: An overview of the entire submission schema.
  model: submission.yaml
  tree_root: true
  include_attributes: false
- title: Sample & Individual
  description: Focusses on the relation between Sample and Individual.
  model: submission.yaml
  classes: ["Sample", "Individual"]
  tree_root: false
  include_attributes: false
- title: Experiment, Sample, & File
  description: Focusses on the relation between Experiment, Sample, and File.
  model: submission.yaml
  classes: ["Experiment", "Sample", "ResearchDataFile", "ExperimentalMethod"]
  tree_root: false
  include_attributes: false
# - title: Study & Sample
#   description: Focusses on the relation between Study, Condition, and Sample.
#   model: submission.yaml
#   classes: ["Study", "Sample"]
#   tree_root: false
#   include_attributes: false
- title: Sample & Individual (with attributes)
  description: Focusses on the details of the relation between Sample, Biospecimen, and Individual.
  model: submission.yaml
  classes: ["Sample", "Individual"]
  tree_root: false
  include_attributes: true
- title: Experiment, Sample, & File (with attributes)
  description: Focusses on the relation between Experiment, Sample, and File.
  model: submission.yaml
  classes: ["Experiment", "Sample", "ResearchDataFile", "ExperimentalMethod"]
  tree_root: false
  include_attributes: true
# - title: Study & Sample (with attributes)
#   description: Focusses on the relation between Study, Condition, and Sample.
#   model: submission.yaml
#   classes: ["Study", "Sample"]
#   tree_root: false
#   include_attributes: true
