classes:
- name: Attribute
  relations: []
- name: AliasMixin
  relations: []
- name: AttributeMixin
  relations:
  - Attributes
- name: Study
  relations: []
- name: SequencingExperiment
  relations:
  - SequencingProtocol
  - LibraryPreparationProtocol
- name: Condition
  relations:
  - Study
- name: LibraryPreparationProtocol
  relations: []
- name: SequencingProtocol
  relations: []
- name: SequencingProcess
  relations:
  - SequencingExperiment
  - Sample
- name: Biospecimen
  relations:
  - Individual
- name: Sample
  relations:
  - Biospecimen
  - Condition
- name: Individual
  relations: []
- name: Trio
  relations:
  - Individual
- name: File
  relations:
  - Dataset
- name: StudyFile
  relations:
  - Study
- name: SampleFile
  relations:
  - Sample
- name: SequencingProcessFile
  relations:
  - SequencingProcess
- name: AnalysisProcessOutputFile
  relations:
  - AnalysisProcess
- name: Analysis
  relations: []
- name: AnalysisProcess
  relations:
  - Analysis
  - StudyFile
  - SampleFile
  - SequencingProcessFile
- name: Dataset
  relations:
  - DataAccessPolicy
- name: DataAccessPolicy
  relations:
  - DataAccessCommittee
- name: DataAccessCommittee
  relations: []
- name: Publication
  relations:
  - Study
