# This is a basic workflow to help you get started with Actions

name: Build and update artifacts

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
    paths:
      - src/schema/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-schema:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the schema
        run: |
          make all

      - name: Generate derived schemas
        run: |
          make gen-creation-schema-artifacts stage-derived-schemas

      - name: Push artifacts
        run: |
          make all
          if [[ ! -z $(git status -s artifacts) ]]
          then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add artifacts
            git commit -m 'Autogenerate artifacts' artifacts
            git push
          fi
