name: Build Documentation

on: push
 
jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: >-
          pip install -r requirements.txt

      - name: Build docs
        run: >-
          ./scripts/generate_linkml_docs.py src/schema/submission_centric_schema.yaml 











  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Build docs and push to gh-pages
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
        # TODO 

