name: Check entity relationship diagrams

on: push

jobs:
  check-erdiagrams:
    name: check entity relationship diagrams
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: >-
          pip install -r requirements.txt

      - name: check entity relationship diagrams
        run: >-
          ./scripts/update_entity_relations.py --check
