name: Check whether XLSX spreadsheets are up to date

on: push

jobs:
  check-xlsx:
    name: Check whether XLSX spreadsheets are up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: >-
          pip install -r requirements.txt

      - name: Check whether XLSX spreadsheets are up to date
        run: >-
          ./scripts/generate_xlsx.py --check
