name: Check entity relationship diagrams

on: push

jobs:
  check-erdiagrams:
    name: check entity relationship diagrams
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: >-
          pip install -r requirements.txt

      - name: update entity relationship diagrams
        run: |
          cp -T ./docs/entity_relations.md ./docs/entity_relations_backup.md
          ./scripts/update_entity_relations.py

      - name: Push potential changes
        run: |
          if [[ ! -z $(git status -s docs) ]]
          then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add docs
            git commit -a -m 'Autogenerate entity relations'
            git push
          fi
