id: https://w3id.org/GHGA-Base-Metadata-Schema
name: GHGA-Base-Metadata-Schema
description: >-
  The base metadata schema for the German Human Genome-Phenome Archive (GHGA).
version: 0.9.0
imports:
  - linkml:types

prefixes:
  linkml: https://w3id.org/linkml/
  GHGA: https://w3id.org/GHGA/
  SIO: http://semanticscience.org/resource/SIO_
  biolink: https://w3id.org/biolink/vocab/
  EFO: http://www.ebi.ac.uk/efo/EFO_
  COB: http://purl.obolibrary.org/obo/COB_

default_prefix: GHGA

default_range: string

default_curi_maps:
  - obo_context
  - idot_context
  - semweb_context

classes:
  Attribute:
    description: >-
      A key/value pair that further characterizes an entity.
    slots:
      - key
      - key_type
      - value
      - value_type
    exact_mappings:
      - SIO:000614
    slot_usage:
      key:
        description: >-
          The key for an attribute.
        required: true
      key_type:
        description: >-
          A semantic type that characterizes the attribute key. Usually this is a
          term from an ontology.
          For example, 'MAXO:0000616' indicates that the attribute is a measurement
          of oxygen saturation in the blood.
        required: false
      value:
        description: >-
          The value for an attribute. Usually this is a numerical value (without the units).
        required: true
      value_type:
        description: >-
          The value_type that characterizes the attribute value. Usually this is a
          term from an ontology that describes how to interpret the value.
          For example, 'SIO:001413' indicates that the value is to be interpreted as
          a percentage.
        required: false

  AliasMixin:
    mixin: true
    description: Mixin for entities that can be assigned an alias at the time of metadata submission.
    slots:
      - alias
    slot_usage:
      alias:
        required: true

  IdentifiedByAliasMixin:
    mixin: true
    abstract: true
    is_a: AliasMixin
    slot_usage:
      alias:
        identifier: true

  AccessionMixin:
    mixin: true
    description: Mixin for entities that can be assigned a GHGA accession.
    slots:
      - accession
    slot_usage:
      accession:
        required: true

  AttributeMixin:
    mixin: true
    description: Mixin for entities that can have one or more attributes.
    slots:
      - attributes
    slot_usage:
      attributes:
        required: false
        inlined: true
        inlined_as_list: true

slots:
  alias:
    description: The alias for an entity at the time of submission.

  accession:
    description: >-
      A unique GHGA identifier assigned to an entity for the sole purpose of
      referring to that entity in a global scope.

  description:
    description: Description of an entity.
    exact_mappings:
      - SIO:000185

  key:
    description: The key of an attribute.

  key_type:
    description: The semantic type for the key of an attribute.

  value:
    description: The value of an attribute

  value_type:
    description: The semantic type for the value of an attribute.

  attributes:
    description: Key/value pairs corresponding to an entity.
    range: Attribute
    multivalued: true
