id: https://w3id.org/GHGA-Base-Metadata-Schema
name: GHGA-Base-Metadata-Schema
description: >-
  The base metadata schema for the German Human Genome-Phenome Archive (GHGA).
version: 0.9.0
imports:
  - linkml:types

prefixes:
  linkml: https://w3id.org/linkml/
  GHGA: https://w3id.org/GHGA/
  SIO: http://semanticscience.org/resource/SIO_
  biolink: https://w3id.org/biolink/vocab/
  EFO: http://www.ebi.ac.uk/efo/EFO_
  COB: http://purl.obolibrary.org/obo/COB_

default_prefix: GHGA

default_range: string

default_curi_maps:
  - obo_context
  - idot_context
  - semweb_context

subsets:
  restricted:
    description: >-
      Subset of properties that are considered to be restricted.

classes:
  NamedThing:
    abstract: true
    aliases: ["named entity", "entity", "object"]
    description: >-
      A database entity, concept or class. This is a generic class that is the root
      of all the other classes.
    slots:
      - id
      - alias
      - xref
    slot_usage:
      id:
        description: >-
          The internal unique identifier for an entity.
        required: true
      alias:
        description: >-
          The alias (alternate identifier) for an entity.
        required: true
      xref:
        description: >-
          Holds one or more database cross references for an entity.
        required: false

  Person:
    is_a: NamedThing
    abstract: true
    description: >-
      A member of the species Homo sapiens.
    slots:
      - given_name
      - family_name
      - additional_name
    slot_usage:
      given_name:
        required: false
      family_name:
        required: false
      additional_name:
        required: false
    exact_mappings:
      - NCIT:C25190
      - SIO:000498
      - prov:Person

  Committee:
    is_a: NamedThing
    abstract: true
    description: >-
      A group of people organized for a specific purpose.
    slots:
      - name
    slot_usage:
      name:
        required: true

  MaterialEntity:
    is_a: NamedThing
    abstract: true
    description: >-
      A MaterialEntity is a physical entity that is spatially extended, exists as a
      whole at any point in time and has mass.
    exact_mappings:
      - SIO:000004

  BiologicalQuality:
    is_a: NamedThing
    abstract: true
    description: >-
      A BiologicalQuality is a quality held by a biological entity.
    exact_mappings:
      - SIO:000475

  InformationContentEntity:
    is_a: NamedThing
    abstract: true
    description: >-
      A generically dependent continuant that is about some thing.
    exact_mappings:
      - IAO:0000030

  PlannedProcess:
    is_a: NamedThing
    abstract: true
    description: >-
      A process is an entity that exists in time by occurring or happening, has temporal parts and
      always involves and depends on some entity during the time it occurs.
    exact_mappings:
      - EFO:0004542
      - OBI:0000011
      - COB:0000082

  Investigation:
    is_a: PlannedProcess
    abstract: true
    description: >-
      Investigation is the process of carrying out a plan or procedure so as to discover fact
      or information about the object of study.
    slots:
      - title
      - description
    exact_mappings:
      - SIO:000747
      - OBI:0000066

  DataTransformation:
    is_a: PlannedProcess
    abstract: true
    description: >-
      A DataTransformation technique used to analyze and interpret data to gain a better
      understanding of it.
    slots:
      - title
      - description
    exact_mappings:
      - OBI:0200000

  ResearchActivity:
    is_a: PlannedProcess
    abstract: true
    description: >-
      A PlannedProcess executed in the performance of scientific research wherein
      systematic Investigations are performed to establish facts and reach new conclusions
      about phenomena in the world.
    slots:
      - title
      - description
    slot_usage:
      title:
        required: true
      description:
        required: true
    exact_mappings:
      - SEPIO:0000004

  Protocol:
    is_a: InformationContentEntity
    abstract: true
    mixins:
      - attribute_mixin
    description: >-
      A plan specification which has sufficient level of detail and quantitative information
      to communicate it between Investigation agents, so that different Investigation agents
      will reliably be able to independently reproduce the process.
    slots:
      - name
      - type
      - description
      - url
    exact_mappings:
      - OBI:0000272
    slot_usage:
      alias:
        required: true
      name:
        description: >-
          Name of the protocol (eg: Sample extraction_PCR amplification).
        required: true
      type:
        description: >-
          Type of the protocol (eg: Target enrichment).
        required: true
      description:
        description: >-
          Detailed description of the Protocol.
        required: true
      url:
        description: >-
          URL for the resource that describes this Protocol.
        required: true
      xref:
        description: >-
          One or more cross-references for this Protocol. 
          (Eg: manufacturer protocol, protocol from publication etc )
        required: true
      has_attribute:
        description: >-
          One or more attributes that further characterizes this Protocol.
        required: true

  Population:
    is_a: MaterialEntity
    abstract: true
    description: >-
      A Population is a collection of individuals from the same taxonomic class living,
      counted or sampled at a particular site or in a particular area.
    slots:
      - name
    slot_usage:
      name:
        required: true

  DiseaseOrPhenotypicFeature:
    is_a: BiologicalQuality
    abstract: true
    mixins:
      - OntologyClassMixin
    description: >-
      Disease or Phenotypic Feature that the entity is associated with. This entity is a union
      of Disease and Phenotypic Feature and exists to accommodate situations where Disease concepts
      are used interchangeably with Phenotype concepts or vice-versa.
    exact_mappings:
      - biolink:DiseaseOrPhenotypicFeature

  OntologyClassMixin:
    mixin: true
    description: Mixin for entities that represent an class/term/concept from an ontology.
    slots:
      - id
      - concept_identifier
      - concept_name
      - description
      - ontology_name
      - ontology_version
    slot_usage:
      id:
        required: true
      concept_identifier:
        required: false
        description: >-
          The Compact URI (CURIE) that uniquely identifies this ontology class.
      concept_name:
        required: false
      ontology_name:
        required: false
        description: >-
          The name or label (rdfs:label) of an ontology class.
      ontology_version:
        required: false
      description:
        required: false
        description: >-
          The description or definition of an ontology class.

  attribute:
    description: >-
      A key/value pair that further characterizes an entity.
    slots:
      - key
      - key_type
      - value
      - value_type
    exact_mappings:
      - SIO:000614
    slot_usage:
      key:
        description: >-
          The key for an attribute.
        required: true
      key_type:
        description: >-
          A semantic type that characterizes the attribute key. Usually this is a
          term from an ontology.
          For example, 'MAXO:0000616' indicates that the attribute is a measurement
          of oxygen saturation in the blood.
        required: false
      value:
        description: >-
          The value for an attribute. Usually this is a numerical value (without the units).
        required: true
      value_type:
        description: >-
          The value_type that characterizes the attribute value. Usually this is a
          term from an ontology that describes how to interpret the value.
          For example, 'SIO:001413' indicates that the value is to be interpreted as
          a percentage.
        required: false

  accession_mixin:
    mixin: true
    description: Mixin for entities that can be assigned a GHGA accession.
    slots:
      - accession
    slot_usage:
      accession:
        required: true

  ega_accession_mixin:
    mixin: true
    description: Mixin for entities that can be assigned an ega_accession, in addition to GHGA accession.
    slots:
      - ega_accession
    slot_usage:
      ega_accession:
        required: true

  attribute_mixin:
    mixin: true
    description: Mixin for entities that can have one or more attributes.
    slots:
      - has_attribute

  deprecated_mixin:
    mixin: true
    description: Mixin for entities that can be deprecated.
    slots:
      - replaced_by
      - deprecation_date
    slot_usage:
      replaced_by:
        required: true
      deprecation_date:
        required: true

slots:
  id:
    description: An identifier that uniquely represents an entity.
    identifier: true
    in_subset:
      - restricted

  alias:
    description: The alias for an entity.
    in_subset:
      - restricted

  accession:
    description: >-
      A unique GHGA identifier assigned to an entity for the sole purpose of
      referring to that entity in a global scope.

  ega_accession:
    description: >-
      A unique European Genome-Phenome Archive (EGA) identifier assigned to an
      entity for the sole purpose of referring to that entity within the EGA
      federated network.

  given_name:
    description: First name.
    in_subset:
      - restricted

  family_name:
    description: Last name.
    in_subset:
      - restricted

  additional_name:
    description: additional_name(s).
    in_subset:
      - restricted

  name:
    description: The name for an entity.

  type:
    description:
      The type of an entity.
      # Note: Not to be confused with rdf:type

  title:
    description: The title that describes an entity.

  xref:
    description: Database cross references for an entity.
    multivalued: true

  url:
    description: A URL to a resource.

  description:
    description: Description of an entity.
    exact_mappings:
      - SIO:000185

  category:
    description: >-
      The category for this file: Whole Genome Sequencing, Whole Exome Sequencing, etc.

  deprecation_date:
    description: >-
      The timestamp (in ISO 8601 format) when the entity was deprecated.

  replaced_by:
    description: >-
      Refers to the entity which replaces a currently deprecated entity.
    domain: NamedThing
    range: NamedThing

  replaces:
    inverse: replaced_by
    description: >-
      Refers to a deprecated entity that is being replaced_by the current entity.
    domain: NamedThing
    range: NamedThing

  concept_identifier:
    description: >-
      The Compact URI (CURIE) that uniquely identifies a concept from an ontology,
      thesaurus, or terminology.

  concept_name:
    description: >-
      The name or label (typically, rdfs:label) of concept from an ontology, thesaurus,
      or terminology.

  ontology_name:
    description: >-
      The name of the ontology from which this ontology class was chosen.

  ontology_version:
    description: >-
      The version of the ontology from which this ontology class was chosen.

  key:
    description: The key of an attribute.

  key_type:
    description: The semantic type for the key of an attribute.

  value:
    description: The value of an attribute

  value_type:
    description: The semantic type for the value of an attribute.

  has_attribute:
    description: Key/value pairs corresponding to an entity.
    range: attribute
    in_subset:
      - restricted
    multivalued: true
    inlined: true
    inlined_as_list: true
